language: node_js
services:
  redis-server
env:
  - DATABASE_URL=postgres://postgres@127.0.0.1/bizwallet
notifications:
  slack: cfa:kkWsa9y5if7z6IE8w7CrsGHh
before_script:
  - psql -c 'create database bizwallet;' -U postgres
  - gulp dbsync
  - gulp build
addons:
  postgresql: "9.3"
node_js:
  '0.10'
branches:
  only:
    - master
    - production
deploy:
  - provider: s3
    access_key_id: AKIAJKINSR3KS7NCOKIQ
    secret_access_key:
      secure: i3IuFD2zBvt5YUDBY0n6QJYj5upGKR9XOQiDqeeHzP6rXx4R9FeWccGAQZAM+fFWM6L3bWU4K92YguHw0AzPhmHOGerlO+KcpuLQqwcO5BtQbXBUlb4QCwfW48KW6ceRlG2WgYEKvF5PswNBGbVVkJKoaDGoc355ior7M59Kq20=
    bucket: bizwallet
    local-dir: public/build
    skip_cleanup: true
    on:
      branch: production
  - provider: s3
    access_key_id: AKIAJKINSR3KS7NCOKIQ
    secret_access_key:
      secure: i3IuFD2zBvt5YUDBY0n6QJYj5upGKR9XOQiDqeeHzP6rXx4R9FeWccGAQZAM+fFWM6L3bWU4K92YguHw0AzPhmHOGerlO+KcpuLQqwcO5BtQbXBUlb4QCwfW48KW6ceRlG2WgYEKvF5PswNBGbVVkJKoaDGoc355ior7M59Kq20=
    bucket: bizwallet-staging
    local-dir: public/build
    skip_cleanup: true
    on:
      branch: master
  - provider: heroku
    api_key:
      master:
        secure: rN6DMbMNXh0X6GSJk1RMVP8mtWnkB71pmI5/ypMe6eHti1JgD7y2SF7AW6p770S0PVwMr1PIY301msmIsZ/8+i0Sov4Quuj9QqknBBwd2H8iEhtEepBF+H3mTKFJKSd1C+klodsbsJr+H4N/PdcLY7VLfqIY1pLQ9+gKv69dlBs=
      production:
        secure: o1ALDx9zYsdJXiadb8tTv3BmMA+2TKbICMp2K/in8TzMXueH4k7cu+aYndlClDlu2daNTplp2AyVu54Q0xDervHeHTU/YIiVImKKrrMZ9AVHB2RlJOG5YhmAC6K+T2IwhLDEuGJZXCy+nzOpihL2/oudlFJUj8X4ytEDIDw1REY=
    app:
      master: bizwallet-staging
      production: bizwallet
    on:
      repo: CoquiCoders/bizwallet
    run:
      - "restart"
      - "gulp prodBuild"


