language: node_js
services:
  - mongodb
node_js:
  - '0.10'
deploy:
  provider: heroku
  api_key:
    secure: sBTSFu2fqUMjrYkeVynHzn90HTXQF4hkBCyebUk+Y3jF9MaHD7nZmZn/teGkuNILtCYwohYZvWc6rYxYrLXhjhenU5uaN85b7FFlu1XG6MRGBv47+UALOH5C/6HhV50ItBq0/U0+CorlA5w0M0pbngnooyoeEojniqa5CjvRB4o=
  app: bizwallet
  on:
    repo: CoquiCoders/bizwallet
  run:
    - restart
