language: node_js
services:
  redis-server
env:
  - DATABASE_URL=postgres://postgres@127.0.0.1/bizwallet MAIL_HANDLER=stub
notifications:
  slack: cfa:kkWsa9y5if7z6IE8w7CrsGHh
  webhooks: http://project-monitor.codeforamerica.org/projects/4b795a27-37e0-4d41-8b25-b580f623c1b4/status
before_script:
  - psql -c 'create database bizwallet;' -U postgres
  - gulp dbsync
  - gulp build
addons:
  postgresql: "9.3"
node_js:
  '0.10'
branches:
  only:
    - master
    - production
deploy:
  - provider: s3
    access_key_id: AKIAJKINSR3KS7NCOKIQ
    secret_access_key:
      secure: JyiuTr7Mo5CiFshcLagv/fkKtdVTW7gc8lEZ/s4ctV1Flg7RNJXv2/rnawE0UNJbsx+qkR0B8eI8V0kghDzmNrdEHw2WMXlLiOTQcYJ8CCjY4WtikizT9/dV4fg8CAqyqaUaKch0AcUR8h6/q2Sq+nPshHs1nUDPLbhGoNxzIg8=
    bucket: bizwallet
    local-dir: public/build
    skip_cleanup: true
    on:
      branch: production
  - provider: s3
    access_key_id: AKIAJKINSR3KS7NCOKIQ
    secret_access_key:
      secure: JyiuTr7Mo5CiFshcLagv/fkKtdVTW7gc8lEZ/s4ctV1Flg7RNJXv2/rnawE0UNJbsx+qkR0B8eI8V0kghDzmNrdEHw2WMXlLiOTQcYJ8CCjY4WtikizT9/dV4fg8CAqyqaUaKch0AcUR8h6/q2Sq+nPshHs1nUDPLbhGoNxzIg8=
    bucket: bizwallet-staging
    local-dir: public/build
    skip_cleanup: true
    on:
      branch: master
  - provider: heroku
    strategy: git
    api_key:
      master:
        secure: oiMMOUAqJ8V9DGn8MDNnTZZVhiaFMMibsebhtw7NVYKE0kKBKvpBb61EoDWG7DYQ0M/ipnL4MVd4WS853tk0Wjqdy/zlcjV+skoq8pmTVqyqG4OkbLPfF7B73x/6FZj4+juyezwEtcTjw6F5JzjCWAvh429L9TX/B3FWiX9togA=
      production:
        secure: ACPvM4AiUazlzwgGT5nysW/xtKSFE8+7b/cebEwZ30X8CFiTczlqwCNB/YkmklAEIqxpgMR7eWLoRs63LSORETbBz6MoDTSrTXffFnWEKobt/trhoJUs1ZxhRvc1amrkrwyoMMdyD+oCbZw63vuf7FZxX+XJhmrK1KKTnQ1v0jQ=
    app:
      master: bizwallet-staging
      production: bizwallet
    on:
      repo: codeforamerica/primerpeso
    run:
      - "gulp migrate"
      - restart


